
export const CONFIG = {
    MAX_ACCESS_TOKEN_LENGTH: 64,
    MAX_UUID_LENGTH: 64,
    SESSION_TOKEN_LENGTH: 64,
    MAX_SESSION_TOKEN_LENGTH: 256,
    REFRESH_TOKEN_LENGTH: 64,
    MAX_REFRESH_TOKEN_LENGTH: 256,
    SESSION_TOKEN_VALID_TIME: 60 * 60 * 24, // 1 day
    REFRESH_TOKEN_VALID_TIME: 60 * 60 * 24 * 7, // 1 week
    LEGITIDEVS: {
        MAX_WORLD_DESCRIPTION_LENGTH: 1024,
        MAX_WORLD_COMMENT_LENGTH: 1024,
    },
    MAX_REQUEST_BODY_LENGTH: 2000,
}